GET http://localhost:8000/v1/products

### POST http://localhost:8000/v1/products/create Content-Type: application/x-www-form-urlencoded

name= Tshirts &quantity=100

### DELETE http://localhost:8000/v1/products/6285127d42bb8368d8d8b88a

### POST http://localhost:8000/v1/products/6285127d42bb8368d8d8b88a/update_quantity/?number=100

### **** DEPLOYMENT TEST ******* GET https://ecom-api-proj.herokuapp.com/v1/products

### POST https://ecom-api-proj.herokuapp.com/v1/products/create Content-Type: application/x-www-form-urlencoded

name=Tshirts &quantity=50

### DELETE https://ecom-api-proj.herokuapp.com/v1/products/6285127d42bb8368d8d8b88a

### POST https://ecom-api-proj.herokuapp.com/v1/products/6285127d42bb8368d8d8b88a/update_quantity/?number=100 HTTP/1.1
